# Generated by Django 5.2.1 on 2025-11-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_category_blogpost_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog/"),
        ),
    ]
