name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        run: |
          cd /home/cemc/vlogetta
          git pull

      - name: Build and restart container
        run: |
          cd /home/cemc/vlogetta
          docker compose build
          docker compose up -d
